net8x: urlopen doesn't support 'with' statement
because urlopen class doesn't provide an exit function.

This fixes

ERROR:r4d.powerservice:power: change status of juno64 failed: addinfourl instance has no attribute '__exit__'
Traceback (most recent call last):
  File "./r4dcfg", line 177, in <module>
    ret = power.change (eargs.name, 1)
  File "/home/local/projects/ci-test/rtl/r4d/r4d/powerservice.py", line 123, in change
    detail = e)
pysimplesoap.server.SoapFault

Signed-off-by: Manuel Traut <manut@linutronix.de>
Reviewed-by: Martin Kaistra <djfun@linutronix.de>